<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [ 
            ['name' => 'Albania'],
            ['name' => 'Algeria'],
            ['name' => 'American Samoa'],
            ['name' => 'Angola'],
            ['name' => 'Anguilla'],
            ['name' => 'Antigua & Barbuda'],
            ['name' => 'Argentia'],
            ['name' => 'Argentina'],
            ['name' => 'Aruba'],
            ['name' => 'Australia'],
            ['name' => 'Bahamas'],
            ['name' => 'Bahrain'],
            ['name' => 'Bangladesh'],
            ['name' => 'Barbados'],
            ['name' => 'Belgium'],
            ['name' => 'Belize'],
            ['name' => 'Benin'],
            ['name' => 'Bermuda'],
            ['name' => 'Brazil'],
            ['name' => 'Brunei'],
            ['name' => 'Bulgaria'],
            ['name' => 'Cambodia'],
            ['name' => 'Cameroon'],
            ['name' => 'Canada'],
            ['name' => 'Cape Verde'],
            ['name' => 'Cayman Island'],
            ['name' => 'Chile'],
            ['name' => 'China'],
            ['name' => 'Colombia'],
            ['name' => 'Comoros'],
            ['name' => 'Congo D.R.'],
            ['name' => 'Congo Rep.'],
            ['name' => 'Cook Islands'],
            ['name' => 'Costa Rica'],
            ['name' => 'Croatia'],
            ['name' => 'Cyprus'],
            ['name' => 'Denmark'],
            ['name' => 'Djibouti'],
            ['name' => 'Domican Republic'],
            ['name' => 'Dominica'],
            ['name' => 'Dominican Republic'],
            ['name' => 'East Timor'],
            ['name' => 'Ecuador'],
            ['name' => 'Egypt'],
            ['name' => 'El Salvador'],
            ['name' => 'Equador'],
            ['name' => 'Equatorial Guinea'],
            ['name' => 'Eritrea'],
            ['name' => 'Estonia'],
            ['name' => 'Falkland Islands'],
            ['name' => 'Faroe Islands'],
            ['name' => 'Fiji'],
            ['name' => 'Finland'],
            ['name' => 'France'],
            ['name' => 'French Polynesia'],
            ['name' => 'Gabon'],
            ['name' => 'Gambia'],
            ['name' => 'Georgia'],
            ['name' => 'Germany'],
            ['name' => 'Ghana'],
            ['name' => 'Gibraltar'],
            ['name' => 'Greece'],
            ['name' => 'Greenland'],
            ['name' => 'Grenada'],
            ['name' => 'Guadeloupe'],
            ['name' => 'Guam'],
            ['name' => 'Guatemala'],
            ['name' => 'Guinea'],
            ['name' => 'Guinea-Bissau'],
            ['name' => 'Guyana'],
            ['name' => 'Guyane'],
            ['name' => 'Haiti'],
            ['name' => 'Honduras'],
            ['name' => 'Iceland'],
            ['name' => 'India'],
            ['name' => 'Indonesia'],
            ['name' => 'Iraq'],
            ['name' => 'Ireland'],
            ['name' => 'Israel'],
            ['name' => 'Italy'],
            ['name' => 'Ivory Coast'],
            ['name' => 'Jamaica'],
            ['name' => 'Japan'],
            ['name' => 'Jordan'],
            ['name' => 'Kenya'],
            ['name' => 'Kiribati'],
            ['name' => 'Kuwait'],
            ['name' => 'Latvia'],
            ['name' => 'Lebanon'],
            ['name' => 'Liberia'],
            ['name' => 'Libya'],
            ['name' => 'Lithuania'],
            ['name' => 'Madagascar'],
            ['name' => 'Malaysia'],
            ['name' => 'Maldives'],
            ['name' => 'Malta'],
            ['name' => 'Marshall Island'],
            ['name' => 'Martinique'],
            ['name' => 'Mauritania'],
            ['name' => 'Mauritius'],
            ['name' => 'Mayotte'],
            ['name' => 'Mexico'],
            ['name' => 'Micronesia'],
            ['name' => 'Monaco'],
            ['name' => 'Montenegro'],
            ['name' => 'Morocco'],
            ['name' => 'Mozambique'],
            ['name' => 'Myanmar'],
            ['name' => 'Namibia'],
            ['name' => 'Nauru'],
            ['name' => 'Netherlands'],
            ['name' => 'Netherlands Antilles'],
            ['name' => 'New Caledonia'],
            ['name' => 'New Zealand'],
            ['name' => 'Nicaragua'],
            ['name' => 'Nigeria'],
            ['name' => 'Norway'],
            ['name' => 'Oman'],
            ['name' => 'Pakistan'],
            ['name' => 'Panama'],
            ['name' => 'Papua New Guinea'],
            ['name' => 'Peru'],
            ['name' => 'Philippines'],
            ['name' => 'Poland'],
            ['name' => 'Portugal'],
            ['name' => 'Puerto Rico'],
            ['name' => 'Qatar'],
            ['name' => 'Reunion'],
            ['name' => 'Romania'],
            ['name' => 'Samoa'],
            ['name' => 'Sao Tome & Principe'],
            ['name' => 'Saudi Arabia'],
            ['name' => 'Senegal'],
            ['name' => 'Seychelles'],
            ['name' => 'Sierra Leone'],
            ['name' => 'Singapore'],
            ['name' => 'Slovenia'],
            ['name' => 'Solomon Islands'],
            ['name' => 'Somalia'],
            ['name' => 'South Africa'],
            ['name' => 'South Korea'],
            ['name' => 'Spain'],
            ['name' => 'Sri Lanka'],
            ['name' => 'St. Christopher & Nievis'],
            ['name' => 'St. Helena'],
            ['name' => 'St. Lucia'],
            ['name' => 'St. Pierre & Miquelon'],
            ['name' => 'St. Vincent & The Grenadines'],
            ['name' => 'Sudan'],
            ['name' => 'Suriname'],
            ['name' => 'Sweden'],
            ['name' => 'Switzerland'],
            ['name' => 'Taiwan'],
            ['name' => 'Tanzania'],
            ['name' => 'Thailand'],
            ['name' => 'Togo'],
            ['name' => 'Tonga'],
            ['name' => 'Trinidad & Tobago'],
            ['name' => 'Tunisia'],
            ['name' => 'Turkey'],
            ['name' => 'Turks & Caicos Islands'],
            ['name' => 'Tuvalo'],
            ['name' => 'U.S.A.'],
            ['name' => 'Ukraine'],
            ['name' => 'United Arab Emirates'],
            ['name' => 'United Kingdom'],
            ['name' => 'Uruguay'],
            ['name' => 'Vanuatu'],
            ['name' => 'Vietnam'],
            ['name' => 'Virgin Islands'],
            ['name' => 'Virgin Islands (UK)'],
            ['name' => 'Virgin Islands (USA)'],
            ['name' => 'Yemen'],
          ];

        DB::table('countries')->insert($countries);
    }
}
